#ifndef __PROGINFO__
#define __PROGINFO__

#define PROGRAM_NAME "BlockBreakC"
#define PROGRAM_VERSION "1.2"

#define RENDER_WIDTH 640
#define RENDER_HEIGHT 472

#define PLAYER_SPEED RENDER_WIDTH / 80
#define PLAYER_WIDTH RENDER_WIDTH / 40
#define PLAYER_HEIGHT RENDER_WIDTH / 40
#define PLAYER_START_X (RENDER_WIDTH / 2) - (PLAYER_WIDTH / 2)
#define PLAYER_START_Y RENDER_HEIGHT - (PLAYER_HEIGHT * 3)

#define SCREEN_EDGE_UP 0
#define SCREEN_EDGE_DOWN RENDER_HEIGHT - PLAYER_HEIGHT
#define SCREEN_EDGE_LEFT 0
#define SCREEN_EDGE_RIGHT RENDER_WIDTH - PLAYER_WIDTH

#define MAX_BLOCKS 255
#define MAX_FPS 30
#define MAX_MS (1000 / MAX_FPS)

#endif
